# Generated by Django 5.0.3 on 2024-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RegNo', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Domian', models.CharField(max_length=100)),
            ],
        ),
    ]
